services:
  - type: web
    name: solana-fellowship-server
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/solana-fellowship-server
    envVars:
      - key: PORT
        value: 10000
      - key: RUST_LOG
        value: info 